desc = 
[
[ "FFG", [
    [   12493, "Twilight Imperium III"                                       ] ,
    [[  22821, "Shattered Empire"                                            ]],
    [[  95802, "Shards of the Throne"                                        ]],
    [  233078, "Twilight Imperium IV"                                        ] ,
    [[ 315895, "Prophecy of Kings"                                           ]],
    [   59294, "Runewars"                                                    ] ,
    [[ 102889, "Banners of War"                                              ]],
    [[  62329, "Jonas The Kind"                                              ]],
    [[  62325, "Nara The Fang"                                               ]],
    [[  62327, "Tobin Farslayer"                                             ]],
    [[  62349, "Truthseer Kel"                                               ]],
    [  187645, "Star Wars: Rebellion"                                        ] ,
    [[ 226840, "Rise of the Empire"                                          ]],
    [   43111, "Chaos in the Old World"                                      ] ,
    [[  95619, "The Horned Rat"                                              ]],
    [   15987, "Horreur à Arkham"                                            ] ,
    [[  25945, "Le Roi en Jaune"                                             ]],
    [[  95683, "La malédiction du Pharaon Noir"                              ]],
    [[  37008, "La Chèvre Noire des Bois"                                    ]],
    [[  67208, "Le Rôdeur devant le Seuil"                                   ]],
    [[  21059, "L'Horreur de Dunwich"                                        ]],
    [[  31536, "L'Horreur de Kinsport"                                       ]],
    [[  40776, "L'Horreur d'Innsmouth"                                       ]],
    [[  93465, "L'Horreur de Miskatonic"                                     ]],
    [  205637, "Arkham à Horror - The card game"                             ] ,
    [  175155, "Forbidden Stars"                                             ] ,
  ]
],
[ "Race for the Galaxy", [
    [   28143, "Race for the Galaxy"                                         ] ,
    [[  34499, "The Gathering Storm"                                         ]],
    [[  40210, "Rebels vs Imperium"                                          ]],
    [[  66121, "The Brink of War"                                            ]],
    [[  92932, "Alien Artifacts"                                             ]],
    [[ 161599, "Xeno Invasion"                                               ]],
    [[ 242309, "New worlds promo"                                            ]],
    [[ 268829, "Retrofit cards"                                              ]],
    [[ 270439, "Expansion and Brinkmanship"                                  ]],
    [[ 394555, "Xeno-Counterstrike"                                          ]],
    [  132531, "Roll for the Galaxy"                                         ] ,
    [[ 211347, "Terraforming Colony/Diversified Economy promo tile"          ]],
    [[ 175754, "Ambition"                                                    ]],
    [[ 269734, "Rivalry"                                                     ]],
    [  205597, "Jump Drive"                                                  ] ,
  ]
],
[ "The 7th Continent", [
    [  180263, "The 7th Continent"                                           ] ,
    [[ 183660, "Le labyrinthe de glace"                                      ]],
    [[ 184186, "Le sanctuaire interdit"                                      ]],
    [[ 184904, "Le marais de l’épouvante"                                    ]],
    [[ 185743, "Le chemin de pénitence"                                      ]],
    [[ 186381, "Craignez les dévoreurs"                                      ]],
    [[ 186987, "Face aux éléments"                                           ]],
    [[ 236206, "Dans les airs, sous la terre"                                ]],
    [[ 237497, "Les Racines Volantes"                                        ]],
    [[ 236854, "Lâcher la Bête !"                                            ]],
    [[ 234094, "Promo cards"                                                 ]],
    [[ 186844, "Print and play demo"                                         ]],
    [[ 186151, "Action deck discard"                                         ]],
    [  286063, "The 7th Citadel"                                             ] ,
    [[ 320287, "Aux frontières du péril"                                     ]],
    [[ 321043, "Les dénicheuses"                                             ]],
    [[ 321511, "Le savoir est un pouvoir"                                    ]],
    [[ 321609, "L’alambic de Valengarde"                                     ]],
    [[ 321678, "Le dernier trône"                                            ]],
    [[ 422617, "Le premier jardin"                                           ]],
    [[ 422618, "Le Renversement"                                             ]],
    [[ 422946, "Trois bons compagnons"                                       ]],
    [[ 423027, "Vestiges oubliés"                                            ]],
    [[ 423028, "Rat de bibliothèque"                                         ]],
  ]
],
[ "RPG", [
    [  124708, "Mice and Mystics"                                            ] ,
    [[ 159458, "Downwood Tales"                                              ]],
    [[ 144777, "Heart of Glorm"                                              ]],
    [[ 132975, "Lost Chapter: Cat's Cradle"                                  ]],
    [[ 148524, "Lost Chapter: The Ghost of Castle"                           ]],
    [[ 134059, "Tattered Threads of Reason"                                  ]],
    [[ 134060, "Needle Rapier"                                               ]],
    [[ 165775, "Toppers"                                                     ]],
    [[ 165774, "Turtle Shell"                                                ]],
    [  179820, "Tail Feathers"                                               ] ,
    [  127398, "Andor"                                                       ] ,
    [[ 136986, "La Légende de Gardétoile"                                    ]],
    [[ 151825, "Nouveaux Héros"                                              ]],
    [[ 156318, "Voyage vers le Nord"                                         ]],
    [[ 228673, "Le Coffret Bonus"                                            ]],
    [[ 255682, "Les Légendes Oubliées"                                       ]],
    [[ 202175, "Héros Sombres"                                               ]],
    [  198287, "Le Dernier Espoir"                                           ] ,
    [  271264, " La liberation de Rietburg"                                  ] ,
    [  177079, "Chada & Thorn"                                               ] ,
    [  195421, "Near and Far"                                                ] ,
    [[ 236667, "Amber Mines"                                                 ]],
    [  255984, "Sleeping Gods"                                               ] ,
    [[ 287670, "Dungeons"                                                    ]],
    [[ 283766, "Tides of Ruin"                                               ]],
  ]
],
[ "Top games", [
    [   36932, "Claustrophobia"                                              ] ,
    [[ 100527, "De Profundis"                                                ]],
    [[ 162409, "Furor Sanguinis"                                             ]],
    [   79828, "A Few Acres of Snow"                                         ] ,
    [   12333, "Twilight Struggle"                                           ] ,
    [  228411, "Iron Curtain"                                                ] ,
    [  132018, "Churchill"                                                   ] ,
    [   45986, "Stronghold"                                                  ] ,
    [[  72851, "Undead"                                                      ]],
    [  179460, "Stronghold-V2"                                               ] ,
    [   96848, "Mage Knight"                                                 ] ,
    [[ 130704, "The Lost Legion"                                             ]],
    [[ 144763, "Krang Character Expansion"                                   ]],
    [[ 176130, "shades of Tezla"                                             ]],
    [[ 248562, "Ultimate Edition"                                            ]],
    [[ 416403, "The Apocalypse Dragon"                                       ]],
    [  169786, "Scythe"                                                      ] ,
    [[ 199727, "Invaders from Afar"                                          ]],
    [[ 223555, "Wind Gambit"                                                 ]],
    [[ 242277, "The Rise of Fenris"                                          ]],
    [[ 262151, "Encounters"                                                  ]],
    [[ 279304, "Modular board"                                               ]],
    [[ 211733, "Factory Cards 13-18"                                         ]],
    [[ 211732, "Objective Cards 24-27"                                       ]],
    [[ 211731, "Encounter Card 29-32"                                        ]],
    [[ 205121, "Encounter Card 33-36"                                        ]],
    [[ 276229, "Encounter Card 37-42"                                        ]],
    [[ 212879, "Encounter Card 37"                                           ]],
    [[ 204984, "Encounter Card 38"                                           ]],
    [[ 221033, "Encounter Card 39"                                           ]],
    [[ 232176, "Encounter Card 40"                                           ]],
    [[ 232087, "Encounter Card 41"                                           ]],
    [[ 237663, "Encounter Card 42"                                           ]],
    [  251247, "Barrage"                                                     ] ,
    [[ 263711, "The Leeghwater Project"                                      ]],
    [[ 304453, "5 Player expansion"                                          ]],
    [[ 366469, "The Nile Affair"                                             ]],
    [[ 397437, "New Lands: The Colorado Connection"                          ]],
    [[ 397438, "New Lands: Duel"                                             ]],
    [[ 388973, "The Geological Factor"                                       ]],
    [[ 426268, "The Legendary Box"                                           ]],
    [[ 318010, "Executive Officers - pack A"                                 ]],
    [[ 304458, "Executive Officers - pack B"                                 ]],
    [[ 346071, "Executive Officers - pack C"                                 ]],
    [[ 363533, "Executive Officers - pack D"                                 ]],
    [[ 397434, "Executive Officers - pack E"                                 ]],
    [  220308, "Projet Gaia"                                                 ] ,
    [[ 396802, "The Lost Fleet"                                              ]],
    [  418059, " SETI: Search for Extraterrestrial Intelligence"             ] ,
    [[ 430027, "Pluto promo card"                                            ]],
  ]
],
[ "War of the Ring", [
    [    9609, "First edition"                                               ] ,
    [[  18034, "Battles of the Third Age"                                    ]],
    [   60153, "Collectors edition"                                          ] ,
    [  115746, "Second edition"                                              ] ,
    [[ 122328, "Lords of Middle-Earth"                                       ]],
    [[ 179404, "Warriors of Middle-Earth"                                    ]],
    [[ 299490, "Kings of Middle-Earth"                                       ]],
    [[ 188886, "The Breaking of the Fellowship"                              ]],
    [[ 339076, "The Fate of Erebor"                                          ]],
    [[ 132430, "Treebeard"                                                   ]],
    [[ 210039, "Tidings not Burdens"                                         ]],
    [  135219, "The Battle of Five Armies"                                   ] ,
    [  216070, "Hunt for the Ring"                                           ] ,
    [    2228, "War of the Ring - SP1"                                       ] ,
  ]
],
[ "Space Hulk", [
    [    2163, "First edition"                                               ] ,
    [[  13315, "Deathwing"                                                   ]],
    [[  13393, "Genestealer"                                                 ]],
    [[  15401, "Campaigns"                                                   ]],
    [   63091, "Second edition"                                              ] ,
    [   54625, "Third edition"                                               ] ,
    [  165838, "Fourth edition"                                              ] ,
  ]
],
[ "PnP", [
    [      22, "Magic Realm"                                                 ] ,
    [  176070, "Magic Realm Light 30"                                        ] ,
    [[ 194882, "Asterisk expansion"                                          ]],
    [  246256, "Magik Realm"                                                 ] ,
    [   75223, "Utopia Engine"                                               ] ,
    [   28044, "Pocket Civ"                                                  ] ,
    [   61451, "Run Emily Run"                                               ] ,
    [  147299, "Pocket Imperium"                                             ] ,
    [   69851, "Aliens this time its war"                                    ] ,
    [   18246, "Island of D"                                                 ] ,
    [   19212, "Island of D 2"                                               ] ,
    [   34639, "Dungeon of D"                                                ] ,
    [  103400, "Slimes of D"                                                 ] ,
    [   53840, "Adventure of D"                                              ] ,
    [  143255, "Goblins vs Zombies"                                          ] ,
    [   39514, "Galaxy of D"                                                 ] ,
    [   92995, "Fighters of D"                                               ] ,
    [  118014, "Pokemon of D"                                                ] ,
    [   63011, "Patrol Lost"                                                 ] ,
    [  188834, "Secret Hitler"                                               ] ,
    [  170416, "Vast: The Crystal Caverns"                                   ] ,
    [[ 234757, "Fearsome Foes"                                               ]],
    [[ 223998, "Bonus cards"                                                 ]],
    [[ 206057, "Silver Gauntlet promo card"                                  ]],
    [[ 206056, "Treasure Trove promo card"                                   ]],
    [   54835, "Route Z"                                                     ] ,
    [  109143, "Trick or Treat"                                              ] ,
    [  237182, "Root"                                                        ] ,
    [[ 241386, "Riverfolk Expansion"                                         ]],
    [[ 309977, "The Vagabond Pack"                                           ]],
    [[ 272637, "Underworld expansion"                                        ]],
    [[ 272638, "Exiles and Partisans deck"                                   ]],
    [[ 287220, "The Clockwork Expansion"                                     ]],
    [[ 334483, "The Clockwork Expansion 2"                                   ]],
    [[ 334485, "Riverfolk Hirelings pack"                                    ]],
    [[ 334486, "Landmarks pack"                                              ]],
    [[ 336276, "Marauder Hirelings pack"                                     ]],
    [[ 361193, "Underworld Hirelings pack"                                   ]],
    [[ 330149, "The Marauder Expansion"                                      ]],
    [  252399, "Vast: The Mysterious Manor"                                  ] ,
    [[ 284666, "Haunted Hallways"                                            ]],
    [  190761, "History of Civilizations"                                    ] ,
    [  263175, "Torpedo Dice"                                                ] ,
    [  316624, "stationfall"                                                 ] ,
  ]
],
[ "Dixit", [
    [   39856, "Dixit"                                                       ] ,
    [   92828, "Dixit Odyssey"                                               ] ,
    [[ 138547, "Odyssey"                                                     ]],
    [[  55660, "2 - Quest"                                                   ]],
    [[ 119657, "Dixit 3"                                                     ]],
    [[ 121288, "3 - Journey"                                                 ]],
    [[ 145325, "4 - Origins"                                                 ]],
    [[ 156189, "5 - Daydream"                                                ]],
    [[ 174090, "6 - Memories"                                                ]],
    [[ 205761, "7 - Revelations"                                             ]],
    [[ 234553, "8 - Harmonies"                                               ]],
    [[ 256237, "10eme anniversaire"                                          ]],
  ]
],
[ "Le seigneur des anneaux", [
    [     823, "Lord of the Rings"                                           ] ,
    [[   2449, "Friends and Foes"                                            ]],
    [[   3819, "Sauron"                                                      ]],
    [[  22884, "Battlefields"                                                ]],
    [    1426, "La quete"                                                    ] ,
    [    3201, "La Confrontation"                                            ] ,
    [[  18833, "Deluxe edition"                                              ]],
    [    4610, "Le duel"                                                     ] ,
    [  421006, "Duel for Middle-Earth"                                       ] ,
  ]
],
[ "Family", [
    [  201808, "Clank!"                                                      ] ,
    [[ 218103, "Sunken Treasures"                                            ]],
    [[ 245377, "Mummy's Curse"                                               ]],
    [[ 257276, "Gold and Silk"                                               ]],
    [[ 282426, "Expeditions: Temple of the Ape Lords"                        ]],
    [[ 206565, "Dire Wolf promo card"                                        ]],
    [[ 214309, "Brawn vs Boots promo card"                                   ]],
    [[ 223119, "Snack Table promo card"                                      ]],
    [[ 234131, "Wishing Wall promo card"                                     ]],
    [[ 234742, "Siren promo card"                                            ]],
    [[ 233019, "Friendly Watcher promo card"                                 ]],
    [[ 233895, "Enchanted Dice promo card"                                   ]],
    [[ 233950, "Magic Spectacles promo card"                                 ]],
    [[ 264712, "Wand of Time"                                                ]],
    [[ 257694, "Expedition Leader"                                           ]],
    [[ 286274, "Opal Apestone"                                               ]],
    [[ 283292, "Trailblazer"                                                 ]],
    [  308918, "Clank! La grande aventure"                                   ] ,
    [  365717, "Clank! Catacombs"                                            ] ,
    [[ 422869, "Lairs and Lost Chambers"                                     ]],
    [    9209, "Les aventuriers du rail"                                     ] ,
    [   43443, "Castle Panic"                                                ] ,
    [[ 104590, "The Wizard's Tower"                                          ]],
    [[ 169784, "Dark Titan"                                                  ]],
    [[ 140681, "Any color hero"                                              ]],
    [[ 133814, "Crossbow"                                                    ]],
    [[ 106158, "Feather"                                                     ]],
    [[ 204542, "Engines War"                                                 ]],
    [[ 216189, "engines-war-jury-rig-promo"                                  ]],
    [[ 177069, "Tower promo 2015 tabletop day"                               ]],
    [[ 199154, "Tower promo 2016 tabletop day"                               ]],
    [[ 223114, "Tower promo 2017 tabletop day"                               ]],
    [[ 249579, "tower promo 2018 tabletop day"                               ]],
    [[ 281981, "tower promo 2019 tabletop day"                               ]],
    [[ 230811, "Fickle fortune"                                              ]],
    [[ 250913, "All for One"                                                 ]],
    [[ 332629, "Crowns and Quests"                                           ]],
    [  176494, "Isle of Skye"                                                ] ,
    [[ 232226, "Journeyman"                                                  ]],
    [[ 246646, "Druids"                                                      ]],
    [  218804, "Imaginarium"                                                 ] ,
    [[ 314501, "Chimera"                                                     ]],
    [  266192, "Wingspan"                                                    ] ,
    [[ 290837, "Swift Start"                                                 ]],
    [[ 290448, "European Expansion"                                          ]],
    [[ 300580, "Oceania Expansion"                                           ]],
    [  194594, "Dice Forge"                                                  ] ,
    [[ 258003, "Rebellion"                                                   ]],
    [   24068, "Shadow Hunters"                                              ] ,
    [[  34869, "Personnages"                                                 ]],
    [  105624, "Poseidon's Kingdom"                                          ] ,
    [  155821, "Inis"                                                        ] ,
    [[ 255588, "Seasons"                                                     ]],
    [  201921, "Tiny EPIC Quest"                                             ] ,
    [  144529, "Theseus"                                                     ] ,
    [[ 149345, "Extra cards"                                                 ]],
    [[ 164931, "Bots"                                                        ]],
    [[ 182515, "Hunters"                                                     ]],
    [  316554, "Dune Imperium"                                               ] ,
    [[ 342031, "Rise of Ix"                                                  ]],
    [[ 367466, "Immortality"                                                 ]],
    [[ 397598, "Uprising"                                                    ]],
    [  198994, "Hero Realms"                                                 ] ,
    [[ 202100, "La Ruine de Thandar"                                         ]],
    [[ 265270, "Le Village Perdu"                                            ]],
    [  281549, "Beast"                                                        ],
    [[ 385276, "Shattered Isles"                                             ]],
    [[ 399046, "The Great Hunt"                                              ]],
  ]
],
[ "Dominion", [
    [   36218, "Dominion"                                                    ] ,
    [   40834, "Dominion - L'intrigue"                                       ] ,
    [  209418, "Seconde édition"                                             ] ,
    [[  51811, "Rivages"                                                     ]],
    [[  66098, "Alchimie"                                                    ]],
    [[  66690, "Prospérité"                                                  ]],
    [[  90850, "Abondance"                                                   ]],
    [[ 104557, "L'arrière-pays"                                              ]],
    [[ 125403, "L'âge des ténèbres"                                          ]],
    [[ 137166, "Guildes"                                                     ]],
    [[ 171915, "Aventures"                                                   ]],
    [[ 192951, "Empires"                                                     ]],
    [[ 209419, "Intrigue (VO)"                                               ]],
    [[ 232452, "Nocturne (VO)"                                               ]],
    [[ 257673, "Renaissance (VO)"                                            ]],
  ]
],
[ "Coop / solo", [
    [   65244, "L'Île Interdite"                                             ] ,
    [  136063, "Le Désert Interdit"                                          ] ,
    [[ 153748, "Le Désert Interdit Storm Tracker"                            ]],
    [  245271, "Le Ciel Interdit"                                            ] ,
    [[ 265057, "Ledge extender"                                              ]],
    [   71836, "Onirim"                                                      ] ,
    [  156336, "Onirim Second Edition"                                       ] ,
    [[ 168017, "Mirrors"                                                     ]],
    [[ 168018, "Sphinx Diver and Confusion"                                  ]],
    [   94389, "Equilibrion / Urbion"                                        ] ,
    [  426994, "Equilibrion / Urbion Second Edition"                         ] ,
    [  143405, "sylvion"                                                     ] ,
    [[ 174648, "Below ground"                                                ]],
    [  143404, "Castellion"                                                  ] ,
    [  206084, "Nautilion"                                                   ] ,
    [  267127, "Aerion"                                                      ] ,
    [  360843, "Stellarion"                                                  ] ,
    [  376893, "Cyberion"                                                    ] ,
    [  209778, "Magic Maze"                                                  ] ,
    [[ 260658, "Hidden Roles"                                                ]],
    [[ 230359, "Maximum Security"                                            ]],
    [[ 238664, "9 tiles"                                                     ]],
    [[ 234154, "Adventskalender promo"                                       ]],
    [  283135, "Magic Maze on Mars"                                          ] ,
    [  171233, "The Big Book of Madness"                                     ] ,
    [[ 279689, "Le Vème élément"                                             ]],
    [  316412, "The LOOP"                                                    ] ,
    [[ 365130, "Brigade à poils"                                             ]],
    [[ 338324, "La Revanche de Foozilla"                                     ]],
    [  330403, "Moon Adventure"                                              ] ,
  ]
],
[ "Small games", [
    [    9220, "Saboteurs"                                                   ] ,
    [[  91072, "Expansion"                                                   ]],
    [[ 143147, "Compilation"                                                 ]],
    [  148228, "Splendor"                                                    ] ,
    [[ 220653, "Cities"                                                      ]],
    [     478, "Citadels"                                                    ] ,
    [[  13291, "The Dark City"                                               ]],
    [  194879, "Not Alone"                                                   ] ,
    [[ 222738, "Exploration"                                                 ]],
    [[ 209698, "Red Artefact promo card"                                     ]],
    [[ 228389, "Green Artefact promo card"                                   ]],
    [[ 232381, "Yellow Artefact promo card"                                  ]],
    [[ 238130, "Extra promo cards"                                           ]],
    [[ 222739, "Sanctuary"                                                   ]],
    [   70323, "King of Tokyo"                                               ] ,
    [[ 127067, "Power-up"                                                    ]],
    [[ 147183, "Halloween Pack"                                              ]],
    [[ 233076, "Monster Pack 1 King Kong"                                    ]],
    [[ 207292, "Monster Pack 2 Cthulhu"                                      ]],
    [[ 250532, "Monster Pack 3 Anubis"                                       ]],
    [  169654, "Deep Sea Adventure"                                          ] ,
    [[ 349150, "Expansion Die"                                               ]],
    [  200077, "Mint Works"                                                  ] ,
    [  230251, "Mint Delivery"                                               ] ,
    [  282765, "Mint Cooperative"                                            ] ,
  ]
],
[ "Krosmaster", [
    [  112138, "Krosmaster Arena"                                            ] ,
    [[ 145040, "Frigost"                                                     ]],
    [  155827, "Quest"                                                       ] ,
    [  155822, "Junior"                                                      ] ,
  ]
],
[ "Civilization games", [
    [  173346, "7 Wonders - Duel"                                            ] ,
    [[ 202976, "Pantheon"                                                    ]],
    [[ 186069, "Messe Essen"                                                 ]],
    [[ 196339, "Statue of Liberty"                                           ]],
    [[ 228690, "Stonehenge"                                                  ]],
    [  250881, "Dominations: Road to Civilization"                           ] ,
    [[ 267235, "Dynasties"                                                   ]],
    [[ 267236, "Hegemon"                                                     ]],
    [[ 267237, "Provinces"                                                   ]],
    [[ 267234, "Silk Road"                                                   ]],
    [    3633, "Sid Meier's Civilization"                                    ] ,
    [   92319, "Olympos"                                                     ] ,
    [[ 105038, "Oikoumene"                                                   ]],
    [[ 127350, "Expansionnism"                                               ]],
    [   77130, "FFG Civilization"                                            ] ,
    [[ 108415, "Fame and Fortune"                                            ]],
    [[ 142708, "Wisdom and Warfare"                                          ]],
    [   40765, "Clash of Cultures"                                           ] ,
    [[ 146244, "Civilizations"                                               ]],
    [[ 167825, "Aztecs"                                                      ]],
    [  299659, "Clash of Cultures - Monumental edition"                      ] ,
    [  182028, "Through the Ages"                                            ] ,
    [[ 280833, "Leaders and Wonders"                                         ]],
    [   25613, "Roll Through the Ages"                                       ] ,
    [  184424, "Mega Civilization"                                           ] ,
    [[ 267304, "Western Empires"                                             ]],
    [[ 285327, "Western Empires - Special buildings"                         ]],
    [[ 285983, "Eastern Empires - Special buildings"                         ]],
    [  174785, "Mare Nostrum"                                                ] ,
    [[ 180156, "Atlas"                                                       ]],
    [[ 215821, "Mythical Beasts"                                             ]],
    [[ 217468, "Starting Heroes"                                             ]],
    [[ 216601, "Heroes Bible"                                                ]],
    [[ 209701, "Kickstarter exclusives"                                      ]],
    [[ 196028, "Theseus promo card"                                          ]],
    [  233247, "Civilization: A New Dawn"                                    ] ,
    [[ 314014, "Terra Incognita"                                             ]],
    [  196354, "Era of Tribes"                                               ] ,
    [[ 288567, "Modular board"                                               ]],
    [[ 288566, "5/6 players expansion"                                       ]],
    [  267370, "Cities Skylines"                                             ] ,
    [  144041, "Patchistory"                                                 ] ,
    [  318184, "Imperium - Classics"                                         ] ,
    [  318182, "Imperium - Legends"                                          ] ,
  ]
],
[ "Space Trucking", [
    [   31481, "Galaxy Trucker"                                              ] ,
    [[  38378, "The Big Expansion"                                           ]],
    [[  97845, "Another Big Expansion"                                       ]],
    [[ 140068, "Anniversary Edition"                                         ]],
    [[ 144227, "The latest models"                                           ]],
    [[ 182027, "Missions"                                                    ]],
    [  173064, "Leaving Earth"                                               ] ,
    [[ 182732, "Mercury"                                                     ]],
    [[ 190924, "Outer Planets"                                               ]],
    [[ 227951, "Stations"                                                    ]],
    [   47055, "High Frontier"                                               ] ,
    [[  94454, "High Frontier-Poster map"                                    ]],
    [[ 124147, "High Frontier-Colonization"                                  ]],
    [[ 149689, "High Frontier-Interstellar"                                  ]],
    [  172737, "High Frontier 3rd edition"                                   ] ,
    [  174333, "High Frontier Lite"                                          ] ,
    [  281655, "High Frontier 4 all"                                         ] ,
    [[ 304511, "Terawatt"                                                    ]],
    [[ 304512, "Colonization"                                                ]],
    [[ 305726, "Conflict"                                                    ]],
    [[ 333517, "Exodus"                                                      ]],
    [     230, "Merchant of Venus"                                           ] ,
    [[ 131646, "Second Edition"                                              ]],
    [  154857, "Emergence Event"                                             ] ,
    [[ 213715, "Awakening"                                                   ]],
    [   75782, "Phantom League"                                              ] ,
    [[  86049, "Mostly Harmless"                                             ]],
    [[ 116212, "Pilot Academy"                                               ]],
    [[ 111086, "Mostly Harmless - Promo deck"                                ]],
    [[ 132480, "Pilot Academy - Promo deck"                                  ]],
    [   82222, "Xia: Legends of the Drift System"                            ] ,
    [[ 199329, "Embers of a Forsaken Star (2017)"                            ]],
    [[ 200200, "Print and Play Mini Expansion"                               ]],
    [[ 144485, "Sellsword"                                                   ]],
    [  138161, "Firefly"                                                     ] ,
    [[ 149796, "Wash's Lucky Dinosaurs Promo Card (2013)"                    ]],
    [[ 149495, "Mal's Pretty Floral Bonnet Promo Card (2013)"                ]],
    [[ 147736, "Breakin' Atmo (2013)"                                        ]],
    [[ 151953, "Big Damn Heroes Promo Cards (2013)"                          ]],
    [[ 145481, "Artful Dodger (2013)"                                        ]],
    [[ 151953, "Pirates & Bounty Hunters (2014)"                             ]],
    [[ 176331, "Card Pack (2014)"                                            ]],
    [[ 159651, "Blue Sun (2014)"                                             ]],
    [[ 179014, "Kalidasa (2015)"                                             ]],
    [[ 177497, "Jetwash (2015)"                                              ]],
    [[ 177496, "Esmeralda (2015)"                                            ]],
    [[ 197591, "Silverhold Loot Crate (2016)"                                ]],
    [[ 197779, "Fruity Oaty Bar (2016)"                                      ]],
    [[ 212140, "Crime & Punishment (2017)"                                   ]],
    [   38553, "Duck Dealer"                                                 ] ,
  ]
],
[ "Prospect", [
    [   22827, "Starcraft"                                                   ] ,
    [[  38796, "Broodwar"                                                    ]],
    [   21241, "Neuroshima Hex"                                              ] ,
    [  238393, "Monolith Arena"                                              ] ,
    [[ 270849, "Academics"                                                   ]],
    [   37046, "Ghost Stories"                                               ] ,
    [[  47616, "White Moon"                                                  ]],
    [[  95699, "Black Secrets"                                               ]],
    [[  39428, "GuardHouse"                                                  ]],
    [[  59867, "The Village People"                                          ]],
    [[ 110906, "Infernal Die"                                                ]],
    [[ 160481, "Band of Brothers"                                            ]],
    [[ 166161, "Guard Tower"                                                 ]],
    [[ 185242, "Promo pack"                                                  ]],
    [[ 175309, "White Moon Scenarios"                                        ]],
    [[  54833, "Chuck No Rice"                                               ]],
    [[  69467, "Jean Claude Van Rice"                                        ]],
    [[  59967, "B Rice Lee"                                                  ]],
    [[ 110882, "Steven Qi Gal"                                               ]],
    [[ 123920, "The Crazy Shaman"                                            ]],
    [[ 123999, "Green Roots"                                                 ]],
    [[ 123998, "Cursed Children"                                             ]],
    [  233371, "Clank! in Space"                                             ] ,
    [[ 254470, "Apocalypse"                                                  ]],
    [[ 286265, "Cyber Station 11"                                            ]],
    [[ 233378, "Code Red promo card"                                         ]],
    [[ 238527, "Triple Agents promo card"                                    ]],
    [[ 257661, "Whiskers"                                                    ]],
    [  160499, "King of New-York"                                            ] ,
    [[ 193320, "Power-up"                                                    ]],
    [  127023, "Kemet"                                                       ] ,
    [[ 161842, "Ta Seti"                                                     ]],
    [[ 254543, "Seth"                                                        ]],
    [   54998, "Cyclades"                                                    ] ,
    [[  96778, "Hades"                                                       ]],
    [[ 155820, "Titans"                                                      ]],
    [[ 193215, "Monuments"                                                   ]],
    [[   6781, "Crossover Kemet/Cyclades"                                    ]],
    [  192457, "Cry Havoc"                                                   ] ,
    [  255507, "Orbis"                                                       ] ,
    [  167791, "Terraforming Mars"                                           ] ,
    [[ 231965, "Venus Next"                                                  ]],
    [[ 218127, "Hellas   Elysium"                                            ]],
    [[ 247030, "Prelude"                                                     ]],
    [[ 255681, "Colonies"                                                    ]],
    [[ 273473, "Turmoil"                                                     ]],
    [  257759, "The River"                                                   ] ,
    [   18602, "Caylus"                                                      ] ,
    [  284818, "Caylus 1303"                                                 ] ,
    [  220632, "Monster Slaughter"                                           ] ,
    [[ 276907, "Underground"                                                 ]],
    [  172818, "Above and Below"                                             ] ,
    [   98918, "Bios:Genesis"                                                ] ,
    [   97915, "Bios:Megafauna"                                              ] ,
    [[ 221769, "Second Edition"                                              ]],
    [  318450, "Bios:Mesofauna"                                              ] ,
    [   29256, "Origins: How we became human"                                ] ,
    [[ 235555, "Bios:Origins - Second Edition"                               ]],
    [  171662, "Neanderthal"                                                 ] ,
    [  338760, "Imperial Steam"                                              ] ,
    [  373106, "Sky Team"                                                    ] ,
    [[ 404069, "Paris Charles de Gaulle"                                     ]],
    [[ 405208, "Düsseldorf"                                                  ]],
    [  396790, "Nucleum"                                                     ] ,
    [[ 408223, "Australia"                                                   ]],
    [[ 400825, "Half-tiles promo"                                            ]],
    [[ 400823, "Acrylic nucleums promo"                                      ]],
    [  340466, "L'Insondable"                                                ] ,
    [[ 416590, "Surgi des Abysses"                                           ]],
    [  184267, "On Mars"                                                     ] ,
    [[ 278241, "Alien Invasion"                                              ]],
    [[ 278431, "Beacon promo card"                                           ]],
    [   25674, "Khronos"                                                     ] ,
    [   422374, "Lone Wolves"                                                ] ,
    [   28720, "Brass - Lancashire"                                          ] ,
    [[ 201381, "2 player board"                                              ]],
    [  224517, "Brass - Birmingham"                                          ] ,
    [  351648, "Dragons Down"                                                ] ,
    [[ 404519, "Desolation"                                                  ]],
    [[ 412169, "Natives and Legends"                                         ]],
    [[ 438330, "Eastern Reaches"                                             ]],
  ]
]];
